name: Build

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: windows-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Install Rust
      uses: actions-rs/toolchain@v1
      with:
        toolchain: nightly
        profile: minimal
        components: rust-src

    - name: Build project
      run: cargo +nightly build -Z build-std=std,panic_abort -Z build-std-features=panic_immediate_abort --release --target=x86_64-pc-windows-msvc

    - name: Post-build steps
      run: |
        if exist target\x86_64-pc-windows-msvc\release\better-qqnt-x64.dll (
          echo DLL file found
          REM 添加你需要对 DLL 文件执行的操作
        ) else (
          echo DLL file not found
          exit 1
        )
